/** Maps each tool dict-key to 3 related tool dict-keys */
export const RELATED: Record<string, [string, string, string]> = {
  // PDF
  pdfMerge:      ["pdfSplit",     "pdfCompress",  "pdfRotate"],
  pdfSplit:      ["pdfMerge",     "pdfCrop",      "pdfCompress"],
  pdfEdit:       ["pdfAnnotate",  "pdfFormFill",  "pdfWatermark"],
  pdfWatermark:  ["pdfSign",      "pdfEdit",      "imgWatermark"],
  pdfSign:       ["pdfWatermark", "pdfAnnotate",  "pdfFormFill"],
  pdfRotate:     ["pdfCrop",      "pdfCompress",  "pdfEdit"],
  pdfCompress:   ["pdfMerge",     "pdfSplit",     "pdfToJpg"],
  pdfPageNumber: ["pdfEdit",      "pdfMerge",     "pdfAnnotate"],
  pdfToJpg:      ["pdfFromJpg",   "imgCompress",  "pdfCompress"],
  pdfFromJpg:    ["pdfMerge",     "imgToPdf",     "pdfCompress"],
  pdfToWord:     ["convWordToPdf","pdfEdit",      "pdfCompress"],
  pdfLock:       ["pdfUnlock",    "pdfWatermark", "pdfSign"],
  pdfUnlock:     ["pdfLock",      "pdfEdit",      "pdfCompress"],
  pdfCrop:       ["pdfRotate",    "pdfEdit",      "pdfCompress"],
  pdfFormFill:   ["pdfSign",      "pdfEdit",      "pdfAnnotate"],
  pdfAnnotate:   ["pdfEdit",      "pdfSign",      "pdfFormFill"],
  // Image
  imgCompress:   ["imgResize",    "imgConvert",   "imgCrop"],
  imgConvert:    ["imgCompress",  "imgResize",    "imgHeicToJpg"],
  imgRemoveBg:   ["imgCompress",  "imgAddText",   "imgWatermark"],
  imgResize:     ["imgCompress",  "imgCrop",      "imgConvert"],
  imgCrop:       ["imgResize",    "imgRotate",    "imgCompress"],
  imgRotate:     ["imgCrop",      "imgResize",    "imgCompress"],
  imgToPdf:      ["pdfMerge",     "pdfFromJpg",   "pdfCompress"],
  imgHeicToJpg:  ["imgCompress",  "imgConvert",   "imgResize"],
  imgWatermark:  ["imgAddText",   "pdfWatermark", "imgCompress"],
  imgAddText:    ["imgWatermark", "imgRemoveBg",  "imgCompress"],
  // Convert
  convWordToPdf:     ["convExcelToPdf", "convHtmlToPdf",     "pdfCompress"],
  convExcelToPdf:    ["convWordToPdf",  "convHtmlToPdf",     "pdfCompress"],
  convHtmlToPdf:     ["convWordToPdf",  "convMdToPdf",       "pdfCompress"],
  convMdToPdf:       ["convHtmlToPdf",  "convWordToPdf",     "pdfCompress"],
  // Video
  vidCompress:   ["vidConvert",   "vidTrim",      "vidToMp3"],
  vidConvert:    ["vidCompress",  "vidToGif",     "vidTrim"],
  vidMerge:      ["vidTrim",      "vidCompress",  "vidConvert"],
  vidMute:       ["vidTrim",      "vidCompress",  "vidToMp3"],
  vidRotate:     ["vidCompress",  "vidTrim",      "vidConvert"],
  vidToGif:      ["vidConvert",   "vidTrim",      "vidCompress"],
  vidToMp3:      ["vidMute",      "vidTrim",      "vidCompress"],
  vidTrim:       ["vidCompress",  "vidMerge",     "vidToMp3"],
};

/** href for each tool dict-key */
export const TOOL_HREF: Record<string, string> = {
  pdfMerge:      "/pdf/merge",
  pdfSplit:      "/pdf/split",
  pdfEdit:       "/pdf/edit",
  pdfWatermark:  "/pdf/watermark",
  pdfSign:       "/pdf/sign",
  pdfRotate:     "/pdf/rotate",
  pdfCompress:   "/pdf/compress",
  pdfPageNumber: "/pdf/page-number",
  pdfToJpg:      "/pdf/to-jpg",
  pdfFromJpg:    "/pdf/from-jpg",
  pdfToWord:     "/pdf/to-word",
  pdfLock:       "/pdf/lock",
  pdfUnlock:     "/pdf/unlock",
  pdfCrop:       "/pdf/crop",
  pdfFormFill:   "/pdf/form-fill",
  pdfAnnotate:   "/pdf/annotate",
  imgCompress:   "/image/compress",
  imgConvert:    "/image/convert",
  imgRemoveBg:   "/image/remove-bg",
  imgResize:     "/image/resize",
  imgCrop:       "/image/crop",
  imgRotate:     "/image/rotate",
  imgToPdf:      "/image/to-pdf",
  imgHeicToJpg:  "/image/heic-to-jpg",
  imgWatermark:  "/image/watermark",
  imgAddText:    "/image/add-text",
  convWordToPdf:     "/convert/word-to-pdf",
  convExcelToPdf:    "/convert/excel-to-pdf",
  convHtmlToPdf:     "/convert/html-to-pdf",
  convMdToPdf:       "/convert/markdown-to-pdf",
  vidCompress:   "/video/compress",
  vidConvert:    "/video/convert",
  vidMerge:      "/video/merge",
  vidMute:       "/video/mute",
  vidRotate:     "/video/rotate",
  vidToGif:      "/video/to-gif",
  vidToMp3:      "/video/to-mp3",
  vidTrim:       "/video/trim",
};
